# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Coalaborate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for Coalaborate

  ## Networking - Socket
  pod 'Alamofire', '5.4.0'
  
  ## UI
  pod 'SnapKit', '~> 5.0.0'
  pod 'lottie-ios'
  
  ## Utils
  pod 'FormatterKit/TimeIntervalFormatter', '1.8.2'
  pod 'Firebase/Analytics'
  pod 'SwiftLint'

end
